name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install && yarn run deploy
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}