name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: npm i && npm deploy
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}